import os
import re
import shutil
from dataclasses import dataclass
from datetime import datetime
from typing import List, Optional

from pylatex import Command, Document, Itemize, Package
from pylatex.utils import NoEscape, escape_latex


@dataclass
class CompiledReport:
    latex_code: str
    latex_path: str
    pdf_path: Optional[str]
    compiler: Optional[str]


def _extract_section(markdown: str, headings: List[str]) -> str:
    heading_pattern = "|".join(re.escape(h) for h in headings)
    pattern = rf"(?ims)^#+\s*(?:{heading_pattern})\s*$\n(.*?)(?=^#|\Z)"
    match = re.search(pattern, markdown)
    return match.group(1).strip() if match else ""


def _extract_bullets(text: str) -> List[str]:
    if not text:
        return []

    bullets: List[str] = []
    for line in text.splitlines():
        cleaned = re.sub(r"^\s*[-*•]\s+", "", line).strip()
        if cleaned and cleaned != line.strip():
            bullets.append(cleaned)

    return bullets


def _extract_paragraphs(text: str) -> List[str]:
    if not text:
        return []

    blocks = [block.strip() for block in re.split(r"\n\s*\n", text) if block.strip()]
    paragraphs: List[str] = []

    for block in blocks:
        if re.match(r"^\s*[-*•]\s+", block):
            continue
        paragraphs.append(block.replace("\n", " ").strip())

    return paragraphs


def _extract_sources(markdown: str) -> List[str]:
    urls = re.findall(r"https?://[^\s)\]]+", markdown)
    seen = set()
    ordered: List[str] = []

    for url in urls:
        normalized = url.rstrip(".,")
        if normalized not in seen:
            seen.add(normalized)
            ordered.append(normalized)

    return ordered


def _escape_latex(text: str) -> str:
    return str(escape_latex(text))


def _configure_document() -> Document:
    document = Document(
        documentclass="article",
        document_options=["11pt", "a4paper"],
        geometry_options={"margin": "1in"},
    )

    packages = [
        Package("fontenc", options=["T1"]),
        Package("inputenc", options=["utf8"]),
        Package("lmodern"),
        Package("microtype"),
        Package("setspace"),
        Package("xcolor", options=["dvipsnames"]),
        Package("titlesec"),
        Package("fancyhdr"),
        Package("enumitem"),
        Package("booktabs"),
        Package(
            "hyperref",
            options=NoEscape("colorlinks=true,linkcolor=TealBlue,citecolor=SeaGreen,urlcolor=TealBlue"),
        ),
        Package("tcolorbox", options=["most"]),
    ]
    for package in packages:
        document.packages.append(package)

    document.preamble.append(NoEscape(r"\setstretch{1.08}"))
    document.preamble.append(NoEscape(r"\setlist[itemize]{leftmargin=1.4em,itemsep=0.35em,topsep=0.35em}"))
    document.preamble.append(Command("definecolor", arguments=["BrandTeal", "HTML", "0D9488"]))
    document.preamble.append(Command("definecolor", arguments=["BrandCreme", "HTML", "FAF4E8"]))
    document.preamble.append(Command("definecolor", arguments=["BrandInk", "HTML", "1F2937"]))
    document.preamble.append(Command("definecolor", arguments=["BrandMuted", "HTML", "475569"]))
    document.preamble.append(NoEscape(r"\pagestyle{fancy}"))
    document.preamble.append(NoEscape(r"\fancyhf{}"))
    document.preamble.append(NoEscape(r"\lhead{ResearchMind Report}"))
    document.preamble.append(NoEscape(r"\rhead{\today}"))
    document.preamble.append(NoEscape(r"\cfoot{\thepage}"))
    document.preamble.append(NoEscape(r"\renewcommand{\headrulewidth}{0.3pt}"))
    document.preamble.append(NoEscape(r"\renewcommand{\footrulewidth}{0pt}"))
    document.preamble.append(
        NoEscape(r"\titleformat{\section}{\Large\bfseries\color{BrandTeal}}{\thesection}{0.8em}{}")
    )
    document.preamble.append(
        NoEscape(r"\titleformat{\subsection}{\large\bfseries\color{BrandInk}}{\thesubsection}{0.7em}{}")
    )

    return document


def _append_title_page(document: Document, topic: str, compiled_at: str) -> None:
    escaped_topic = _escape_latex(topic)
    document.append(
        NoEscape(
            rf"""
\begin{{titlepage}}
\pagecolor{{BrandCreme}}
\color{{BrandInk}}
\centering
\vspace*{{1.8cm}}
{{\Huge\bfseries Research Report\par}}
\vspace{{0.6cm}}
{{\Large\color{{BrandTeal}} {escaped_topic}\par}}
\vspace{{1.8cm}}
\begin{{tcolorbox}}[width=0.88\textwidth,colback=white,colframe=BrandTeal,boxrule=0.8pt,arc=2mm]
Generated by ResearchMind\\
Compiled at: {compiled_at}\\
Template: Professional technical article format\\
Compiled via PyLaTeX
\end{{tcolorbox}}
\vfill
\end{{titlepage}}
\nopagecolor
"""
        )
    )


def _append_section(document: Document, title: str) -> None:
    document.append(NoEscape(rf"\section*{{{_escape_latex(title)}}}"))
    document.append(NoEscape("\n"))


def _append_paragraphs(document: Document, paragraphs: List[str], empty_message: str) -> None:
    entries = paragraphs if paragraphs else [empty_message]
    for paragraph in entries:
        document.append(_escape_latex(paragraph))
        document.append(NoEscape("\n\n"))


def _append_bullets(document: Document, items: List[str], empty_message: str) -> None:
    with document.create(Itemize()) as itemize:
        if items:
            for item in items:
                itemize.add_item(_escape_latex(item))
        else:
            itemize.add_item(_escape_latex(empty_message))
    document.append(NoEscape("\n"))


def _append_sources(document: Document, urls: List[str]) -> None:
    with document.create(Itemize()) as itemize:
        if not urls:
            itemize.add_item("No sources found in the generated report.")
            return

        for url in urls:
            escaped_label = _escape_latex(url)
            itemize.add_item(NoEscape(rf"\href{{{url}}}{{{escaped_label}}}"))


def build_latex_document(topic: str, markdown: str) -> Document:
    summary_section = _extract_section(markdown, ["Summary", "Abstract", "Overview"])
    findings_section = _extract_section(markdown, ["Key Findings", "Findings", "Insights"])
    gaps_section = _extract_section(markdown, ["Research Gaps", "Limitations", "Open Problems"])
    conclusion_section = _extract_section(markdown, ["Conclusion", "Conclusions"])

    summary_paragraphs = _extract_paragraphs(summary_section)
    findings = _extract_bullets(findings_section)
    gaps = _extract_bullets(gaps_section)
    conclusion_paragraphs = _extract_paragraphs(conclusion_section)
    sources = _extract_sources(markdown)

    compiled_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    document = _configure_document()

    _append_title_page(document, topic, compiled_at)

    _append_section(document, "Executive Summary")
    _append_paragraphs(document, summary_paragraphs, "No summary section was generated.")

    _append_section(document, "Key Findings")
    _append_bullets(document, findings, "Key findings were not explicitly enumerated in the model output.")

    _append_section(document, "Research Gaps and Open Questions")
    _append_bullets(document, gaps, "Research gaps were not explicitly provided by the model output.")

    _append_section(document, "Conclusion")
    _append_paragraphs(
        document,
        conclusion_paragraphs,
        "The generated report did not include a dedicated conclusion section. Synthesize key findings and future work manually if needed.",
    )

    _append_section(document, "References and Sources")
    _append_sources(document, sources)

    return document


def build_latex_report(topic: str, markdown: str) -> str:
    return build_latex_document(topic, markdown).dumps()


def _detect_compiler() -> Optional[str]:
    candidates = ["pdflatex", "xelatex", "lualatex", "tectonic"]

    for compiler in candidates:
        resolved = shutil.which(compiler)
        if resolved:
            return resolved

        local_app_data = os.getenv("LOCALAPPDATA")
        known_paths = []
        if local_app_data:
            known_paths.append(
                os.path.join(local_app_data, "Programs", "MiKTeX", "miktex", "bin", "x64", f"{compiler}.exe")
            )

        known_paths.extend(
            [
                os.path.join("C:\\Program Files", "MiKTeX", "miktex", "bin", "x64", f"{compiler}.exe"),
                os.path.join("C:\\Program Files (x86)", "MiKTeX", "miktex", "bin", "x64", f"{compiler}.exe"),
            ]
        )

        for path in known_paths:
            if os.path.exists(path):
                return path

    return None


def _compiler_args(compiler: str) -> List[str]:
    if compiler == "tectonic":
        return ["--keep-logs", "--keep-intermediates"]

    return ["-halt-on-error"]


def compile_latex_to_pdf(document: Document, output_dir: str, base_name: str = "report") -> tuple[Optional[str], Optional[str]]:
    compiler = _detect_compiler()
    if compiler is None:
        return None, None

    file_path = os.path.join(output_dir, base_name)

    try:
        document.generate_pdf(
            filepath=file_path,
            clean=False,
            clean_tex=False,
            compiler=compiler,
            compiler_args=_compiler_args(compiler),
            silent=True,
        )
    except Exception as error:
        raise RuntimeError(f"PyLaTeX compilation failed: {error}") from error

    pdf_path = f"{file_path}.pdf"
    if not os.path.exists(pdf_path):
        raise RuntimeError("PyLaTeX finished without producing report.pdf")

    return pdf_path, f"pylatex:{compiler}"


def generate_compiled_report(topic: str, markdown: str, output_dir: str) -> CompiledReport:
    os.makedirs(output_dir, exist_ok=True)

    document = build_latex_document(topic, markdown)
    latex_code = document.dumps()
    latex_path = os.path.join(output_dir, "report.tex")

    with open(latex_path, "w", encoding="utf-8") as file:
        file.write(latex_code)

    pdf_path, compiler = compile_latex_to_pdf(document, output_dir)
    return CompiledReport(
        latex_code=latex_code,
        latex_path=latex_path,
        pdf_path=pdf_path,
        compiler=compiler,
    )
